!function(){"use strict";class e{constructor(){this.pathToWorksImages="img/dist/works",this.popUpOverlayEl=document.querySelector(".pop-up__overlay"),this.wrapperEl=document.querySelector("#portfolio-slider .swiper-wrapper"),this.acceptedEl=document.querySelector(".accepted"),this.portfolioEl=document.querySelector(".portfolio"),this.moreEl=document.querySelector(".portfolio__more"),this.settings={slidesPerView:"auto",speed:1200,freeMode:!0,scrollbar:{el:".swiper-scrollbar",draggable:!0},breakpoints:{320:{spaceBetween:5},993:{spaceBetween:0}}},this.numberOfCardsOnDesktop=8,this.numberOfCardsOnTablet=6}insertPortfolioIntoPage(e){this.insertProjectsIntoPage(e),this.addProjectsClickListener(e);let t=this.addSliderPortfolio();this.checkWidthWidth(t),this.setHeightCards(),this.addButtonMore(e),window.addEventListener("resize",()=>{this.insertProjectsIntoPage(e),this.addProjectsClickListener(e),t.update(),this.checkWidthWidth(t),this.setHeightCards(),this.addButtonMore(e)})}insertProjectsIntoPage(e){var t,i=window.innerWidth;let r="",o=(this.wrapperEl.innerHTML="",0);for(t of e)1366<i&&o<this.numberOfCardsOnDesktop||i<=1366&&992<i&&o<this.numberOfCardsOnTablet?(r+=this.getCardMarkup(t),o++):i<=992&&(r+=this.getCardMarkup(t));this.wrapperEl.insertAdjacentHTML("beforeend",r)}getCardMarkup(e){return`
			<div class="swiper-slide">
				<img src="${this.pathToWorksImages}/${e.id}/${e.image}" width="421" height="440" alt="${e.name}" class="portfolio__item" data-id="${e.id}">
			</div>`}addProjectsClickListener(i){document.querySelectorAll(".portfolio__item").forEach(e=>{for(let t of i)e.dataset.id==t.id&&e.addEventListener("click",()=>{var e=this.getPopUpWithFullImage(t);this.popUpOverlayEl.classList.add("active-pop-up"),this.acceptedEl.insertAdjacentHTML("beforebegin",e),this.addCloseElemsClickListener(),this.addImagesElemsClickListener()})})}getPopUpWithFullImage(e){return`
			<div class="image">
				<div class="image__body">
					<img src="${this.pathToWorksImages}/${e.id}/${e.imageBig}" alt="${e.name}" width="1500" height="1058" class="image__picture">
				</div>
				<button class="image__close" type="button">
					<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg" class="image__close-icon">
						<path d="M1.2915 1.29163L16.7082 16.7083" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
						<path d="M16.7082 1.29163L1.2915 16.7083" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
				</button>
			</div>`}addCloseElemsClickListener(){document.querySelectorAll(".image__close").forEach(t=>{t.addEventListener("click",()=>{var e=t.closest(".image");this.popUpOverlayEl.classList.remove("active-pop-up"),e.style.display="none"})})}addImagesElemsClickListener(){document.querySelectorAll(".image").forEach(i=>{i.addEventListener("click",e=>{var t=i.querySelector(".image__body");e.target==t&&(this.popUpOverlayEl.classList.remove("active-pop-up"),i.style.display="none")})})}addSliderPortfolio(){return new Swiper("#portfolio-slider",this.settings)}checkWidthWidth(e){var t=+this.portfolioEl.getBoundingClientRect().width.toFixed(1);e.allowTouchMove=!(992<t)}setHeightCards(){document.querySelectorAll(".portfolio .portfolio__item").forEach(e=>{var t=e.offsetWidth;e.style.height=t+"px"})}addButtonMore(e){var t=document.querySelectorAll(".portfolio .portfolio__item").length,i=e.length;this.moreEl.style.display=t<i?"block":"none",this.addButtonMoreClickListener(e)}addButtonMoreClickListener(i){this.moreEl.addEventListener("click",()=>{let e="";this.wrapperEl.innerHTML="";for(var t of i)e+=this.getCardMarkup(t);this.wrapperEl.insertAdjacentHTML("beforeend",e),this.addProjectsClickListener(i),this.setHeightCards(),this.moreEl.style.display="none"})}findNumberWorks(e,t){return e.filter(function(e){return e.type==t}).length}}window.addEventListener("load",()=>{(new e).insertPortfolioIntoPage(works)})}();